baseURL: https://www.chiaraciscato.com/
languageCode: en-us
title: chiara ciscato
theme: PaperMod
email: chiaraciscato@email.com
copyright: chiara ciscato 


params:
  EnableInstantClick: true
  ShowBreadCrumbs: true
  profile: true
  ShowToc: false
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  disableScrollToTop: false


  profileMode:
      enabled: true
      title: "Hi, I'm Chiara and I am a Climate scientist" 
      subtitle: "My research interests lie in the understanding of global.\n
      as well as local climate change through data-driven storytelling."
      imageUrl: "avatar.png" 
      imageTitle: "chiara" 
      imageWidth: 150
      imageHeight: 150
      buttons:
        - name: tags
          url: "/tags"


  socialIcons: 
        - name: github
          url: https://github.com/chiaraciscato
        - name: linkedin
          url: https://www.linkedin.com/in/chiara-ciscato-3964bb1b7/


menu:
  main:
    - identifier: About
      name: About
      pageRef: /About
      weight: 1
    - identifier: Projects
      name: Projects
      pageRef: /Projects
      weight: 2
    - identifier: Résumé
      name: Résumé
      pageRef: /Résumé
      weight: 3
    - identifier: Write me
      name: Write me
      pageRef: /Write me
      weight: 4


# for help in website building and css modifications
# I refer to (and thank) https://jessewei.dev/blog/2023/papermod/


# important #
# to change font style and size ccWebsite/layouts/partials/extend_head.html